[workspace]
members = [
    "qualinvest_core",
    "qualinvest_cli",
    "qualinvest_server",
    "qualinvest-gui",
    "wasm_graph",
]
exclude = ["finql", "gui_tests"]
resolver = "3"

[profile.release]
lto = true

[workspace.dependencies]
simple_logger = "5.0"
console_log = "1"
log = "0.4"
