[workspace]
members = [
    "qualinvest-core",
    "qualinvest-cli",
    "qualinvest-gui",
    "wasm_graph",
]
exclude = ["finql"]
resolver = "3"

[workspace.package]
version = "0.3.0"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xemwebe/qualinvest"
keywords = ["finance", "investment", "quantitative", "analysis"]

[profile.release]
lto = true

[workspace.dependencies]
finql = { version = "0.14", path = "finql" }
time = { version = "0.3", features = ["local-offset", "serde", "parsing", "macros"] }
console_error_panic_hook = "0.1"
pretty_env_logger = "0.5"
console_log = "1"
log = "0.4"
cal-calc = "0.2"
confy = "2.0.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "time",
    "json",
    "migrate"
] }

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
