debug = false

[db] 
# via http to localhost or remote server
#url = 'postgresql://localhost/qlinvestdb?user=qualinvest&password=<password>&sslmode=disable' 
# via web socket on localhost
url = 'postgresql:///qlinvestdb?user=qualinvest&password=<password>&sslmode=disable' 

[pdf]
doc_path = '<directory path to store documents in>'
warn_old = false
consistency_check = true
rename_asset = false

[market_data]
alpha_vantage_token = "<token>"
gurufocus_token = "<token>"
eod_historical_data_token = "<token>"

[server]
port = 8000
relative_path = ""
secret_key = "cUagfL6pfOZmSrn/3WTDef8tLTdaMSfIwjHCd/EaxPg="
