[package]
name = "qualinvest_server"
version = "0.1.0"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2018"

[dependencies]
rocket = { git="https://github.com/SergioBenitez/Rocket.git" }
serde_json = "1.0"
finql = { version = "0.7", path = "../../finql" }
chrono = "0.4"
qualinvest_core = { version="0.1.2", path="../qualinvest_core" }
rusqlite = "0.23"

[dependencies.rocket_contrib]
git="https://github.com/SergioBenitez/Rocket.git"
default-features = false
features = ["json","postgres_pool"]