[package]
name = "qualinvest-cli"
description = "Command line executable of the qualinvest project"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
finql.workspace = true
time.workspace = true
qualinvest-core = { path = "../qualinvest-core" }
serde.workspace = true
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.1"
chrono = "0.4"
tokio = "1.3"
async-trait = "0.1"
plotters = "0.3"
thiserror = "2.0"
cal-calc = "0.2"
log.workspace = true
pretty_env_logger.workspace = true
bcrypt = "0.19"
rpassword = "7.3"
confy.workspace = true
anyhow.workspace = true
glob = "0.3.4"
